
services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: next_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT= 27017

  mongodb:
    image: mongo:6
    container_name: mongo_db
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
