// src/data/products.ts

export const products = [
  {
    id: "p1",
    title: "Nike Air Force 1 Mid '07",
    subtitle: "Men's Shoes",
    price: 98.3,
    meta: "6 Colour",
    imageSrc: "/shoes/shoe-1.jpg",
    imageAlt: "Nike Air Force 1 Mid 07",
    badgeLabel: "Best Seller",
    badgeTone: "accent",
  },
  {
    id: "p2",
    title: "Nike Court Vision Low Next Nature",
    subtitle: "Men's Shoes",
    price: 98.3,
    meta: "4 Colour",
    imageSrc: "/shoes/shoe-2.webp",
    imageAlt: "Nike Court Vision Low",
    badgeLabel: "Extra 20% off",
    badgeTone: "success",
  },
  {
    id: "p3",
    title: "Nike Dunk Low Retro",
    subtitle: "Men's Shoes",
    price: 98.3,
    meta: "6 Colour",
    imageSrc: "/shoes/shoe-3.webp",
    imageAlt: "Nike Dunk Low Retro",
    badgeLabel: "Extra 10% off",
    badgeTone: "success",
  },

  // Additional products 👇
  {
    id: "p4",
    title: "Nike Air Max 90",
    subtitle: "Men's Shoes",
    price: 129.99,
    meta: "5 Colour",
    imageSrc: "/shoes/shoe-4.webp",
    imageAlt: "Nike Air Max 90",
  },
  {
    id: "p5",
    title: "Nike Air Max 95",
    subtitle: "Men's Shoes",
    price: 149.99,
    meta: "3 Colour",
    imageSrc: "/shoes/shoe-5.avif",
    imageAlt: "Nike Air Max 95",
  },
  {
    id: "p6",
    title: "Nike Air Max 270",
    subtitle: "Women's Shoes",
    price: 159.99,
    meta: "4 Colour",
    imageSrc: "/shoes/shoe-6.avif",
    imageAlt: "Nike Air Max 270",
    badgeLabel: "New Arrival",
    badgeTone: "default",
  },
  {
    id: "p7",
    title: "Nike Pegasus 40",
    subtitle: "Running Shoes",
    price: 119.99,
    meta: "7 Colour",
    imageSrc: "/shoes/shoe-7.avif",
    imageAlt: "Nike Pegasus 40",
  },
  {
    id: "p8",
    title: "Nike Revolution 6",
    subtitle: "Women's Running Shoes",
    price: 69.99,
    meta: "5 Colour",
    imageSrc: "/shoes/shoe-8.avif",
    imageAlt: "Nike Revolution 6",
  },
  {
    id: "p9",
    title: "Nike Blazer Mid '77 Vintage",
    subtitle: "Men's Shoes",
    price: 109.99,
    meta: "6 Colour",
    imageSrc: "/shoes/shoe-9.avif",
    imageAlt: "Nike Blazer Mid 77 Vintage",
  },
  {
    id: "p10",
    title: "Nike Jordan Max Aura 5",
    subtitle: "Jordan Shoes",
    price: 149.99,
    meta: "3 Colour",
    imageSrc: "/shoes/shoe-10.avif",
    imageAlt: "Jordan Max Aura 5",
    badgeLabel: "Best Seller",
    badgeTone: "accent",
  },
];
